import{a as p,S as m,i}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const g="46607456-5552cc86243543e4de6027df0",h="https://pixabay.com/api/";async function w(r,t=1){try{return(await p.get(h,{params:{key:g,q:r,page:t,image_type:"photo",per_page:15}})).data}catch(s){throw console.error("Помилка при отриманні зображень:",s),s}}function b(r){const t=document.querySelector(".gallery"),s=r.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <p>Likes: ${e.likes}</p>
            <p>Views: ${e.views}</p>
            <p>Comments: ${e.comments}</p>
            <p>Downloads: ${e.downloads}</p>
          </div>
        </a>
      `).join("");t.insertAdjacentHTML("beforeend",s);const{height:a}=t.firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}function L(){const r=document.querySelector(".gallery");r.innerHTML=""}const E=document.getElementById("search-form"),v=document.querySelector(".gallery"),l=document.getElementById("load-more"),u=document.getElementById("loader");let n=1,y="",d=0,q=new m(".gallery a",{captionsData:"alt",captionDelay:250});async function f(r=""){try{r&&(n=1,y=r,d=0,L()),u.style.display="block",l.style.display="none";const t=await w(y,n);if(!t||!t.hits||t.hits.length===0){i.warning({title:"No Results",message:"No images found for your query. Please try again!"});return}n===1&&(d=t.totalHits),b(t.hits),q.refresh(),n*15>=d?(l.style.display="none",i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})):(l.style.display="block",n++),B()}catch{i.error({title:"Error",message:"Something went wrong! Please try again later."})}finally{u.style.display="none"}}function B(){const r=v.firstElementChild;if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}E.addEventListener("submit",r=>{r.preventDefault();const t=r.currentTarget.elements.query.value.trim();if(!t){i.error({title:"Error",message:"Please enter a search query!"});return}l.style.display="none",f(t)});l.addEventListener("click",()=>{f()});
//# sourceMappingURL=index.js.map
